import { Inter } from "next/font/google";
import "./globals.css";
import NextUiProvider from "@/providers/nextui-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextUiProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </NextUiProvider>
  );
}
